### ISSUE TITLE
Add a 'Page Updated' note to the Call Outs page

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#71] opened 2023-03-15 15:25 UTC
It would be good to add this, as other pages on the site do - e.g. Volunteers 

![Image](https://user-images.githubusercontent.com/88284441/225358087-a631459e-f89f-4205-aade-7727bfc5c812.png)

**Comment by ODILMichelle** [comment] 2023-04-26 05:34
@gilesdring I know you were looking at page updates yesterday, so thought I would flag this ticket to you. It's perhaps lower priority than other work - but might be a quick fix for someone once you've made any changes you are currently exploring.

**Comment by gilesdring** [comment] 2023-04-26 05:38
![image](https://user-images.githubusercontent.com/1731108/234479030-f162db94-1202-413b-a0e8-b5412118aa80.png)

This is where I've got to. Should be quite easy to generalise. Not sure about the "template updated" parts, but that's closest to what we had before. It's coloured in grey to make it visually distinct. As I was doing it I figured that it would be easy to extend this to be the way of listing sources for the page as well.

**Comment by gilesdring** [comment] 2023-04-26 09:07
Agreed to add this to metrics page template

- [ ] Change Page template to Page layout and text
- [ ] Make source data dependent on this being part

Potential link to #16

**Comment by gilesdring** [comment] 2023-04-26 10:45
Added template  for metadata block in https://github.com/open-innovations/leeds-2023/blob/main/docs/_includes/partials/metadata.njk

Any page with the sources data frontmatter will have the date of the first one displayed. This can be a path to a directory or a file. The date is the time that the path changed according to git. NB if the file/directory has changed, but it's not yet checked into git, it'll not show the new date, but the time it was last changed in git.

**Comment by ODILMichelle** [comment] 2023-04-26 11:56
Thanks for quick work on this. 

Questions/reflections 

a) Do we need the descriptor text (e.g. 'social media statistics' in associated image, given that we have a heading on the page and description on the page?
b) In previous version of this showed above, the metadata was below the introductory text, but this seems to have changed. Was there a specific reason for this decision?



![Image](https://user-images.githubusercontent.com/88284441/234567719-b7bf2dd7-4241-4eee-8fc7-ec89621e1bc2.png)

**Comment by gilesdring** [comment] 2023-04-27 08:32
a) Happy to remove this. It sort of made sense that we include that
b) The issue is that we can't inject this content at an arbitrary place in the page if we want to do it as part of the template. To do this, we'd need to turn all of the introductory matter into a data element then render that as a part of the template. Can do that, but this is fairly clearly outside the scope of this ticket. There might be some sense in doing it, as it would potentially enforce a better structure.
c) I added the About this page to avoid people having to infer what it was! I was also thinking that would make a good target in the event that we want to make the content hideable. Again, happy to remove.

**Comment by ODILMichelle** [comment] 2023-04-27 08:35
a) and c) Could you show me what it looks like with these removed?
b) Lets review this once we've worked out what we think about a and c?

d) (new point) Page layout and text' showing as updated on the 27th across all pages, despite no page layout or text changes having taken place.

**Comment by gilesdring** [comment] 2023-04-27 08:57
Have had a fiddle...

![Image](https://user-images.githubusercontent.com/1731108/234812468-7d36a7c8-4bb9-467b-afb5-0a620f731eaa.png)

**Comment by gilesdring** [comment] 2023-04-27 09:10
And without the extra header 



![Image](https://user-images.githubusercontent.com/1731108/234815353-7efabff4-dd5b-44f0-89bc-7b66dc95b3e2.png)

**Comment by ODILMichelle** [comment] 2023-04-27 15:10
I think I prefer the 'without the 'About this page' text... Feels too much?

**Comment by gilesdring** [comment] 2023-05-02 21:09
Done

**Closed by gilesdring** 2023-05-02 21:09 UTC

**Comment by ODILMichelle** [comment] 2023-05-03 07:17
I have an action here to talk about this with you. Will pick it up seperately
